version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins-ansible
    build:
      context: jenkins-ansible     
    ports:
      - "8081:8080"
    volumes:
      - /home/${USER}/jenkins/jenkins_home:/var/jenkins_home
    networks:
      - net
networks:
  net: