# code-server
#

version: '3.8'
services:
  code-server:
    image: lscr.io/linuxserver/code-server:4.95.3
    container_name: code-server
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /home/${USER}/resources/docker/code-server/appdata:/config
    ports:
      - 8443:8443
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD=${PASSWORD} #optional
      #- HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=${SUDO_PASSWORD} #optional
      #- SUDO_PASSWORD_HASH= #optional
      #- PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional

  networks:
    default:
      external: true
      name: nginx-default
