# uptime-kuma
# 

version: '3.8'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    security_opt:
      - no-new-privileges:true
    volumes:
      - /home/${USER}/resources/docker/kuma/appdata:/app/data
    ports:
      - 3001:3001 # Host Port:Container Port
    env_file:
      -  stack.env

# TODO: Review if external network is still needed before uncommenting
# networks:
#   default:
#     external: true
#     name: nginx-default