# cloudf-tunnel
#

version: '3.8'
services:
  cloudf-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudf-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDF_TUNNEL}
