# cloudf-tunnel
#

version: '3.8'
services:
  cloudf-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudf-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDF_TUNNEL}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    healthcheck:
      test: ["CMD", "cloudflared", "--version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    network_mode: "host"
  
# networks:
#   default:
#     external: true
#     name: cloudfare-default