# neo4j
#

version: '3.7'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: unless-stopped
    volumes:
      - /home/${USER}/resources/docker/neo4j/appdata/data:/data
      - /home/${USER}/resources/docker/neo4j/appdata/logs:/logs
      - /home/${USER}/resources/docker/neo4j/appdata/import:/var/lib/neo4j/import
      - /home/${USER}/resources/docker/neo4j/appdata/plugins:/plugins
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc", "n10s", "graph-data-science"]


# networks:
#   default:
#     external: true
#     name: nginx-default